# Site settings
author: Enrique Marcos
description: TL;DR - Desarrollador
name: enrmarc
url: "http://enrmarc.github.io"
github_username:  enrmarc

# Build settings
excerpt_separator: ""
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM