author:      Enrique Marcos
name:        enrmarc
url:         "http://enrmarc.github.io"
biography:   "I’m Enrique, software developer based in <strike>Spain</strike>,
             Germany, and currently <strike>Java, PHP, Python</strike>, JavaScript pays my bills.
             Currently working on my M.Sc. Thesis
             in the <a href='https://www.uni-due.de'>Universität Duisburg-Essen</a>."
keywords:    "Software Engineering, Mathematics, Programming, Machine-Learning, Artificial Intelligence"
description: "A blog about software, personal projects, and related stuff.
             Sometimes creative, but not necessarily."
colophon:    "© 2012 — 2017 Enrique Marcos.<br>
             Content available under Creative Commons (BY-NC-SA) unless otherwise noted.<br>
             This site is hosted at <a href='https://pages.github.com/''>Github Pages</a>
             and created with <a href='http://jekyllrb.com/''>Jekyll</a>."
highlighter: rouge
encoding:    "utf-8"
baseurl:     ""
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir:  assets/css

#permalink: /blog/:year/:month/:day/:title/
#gems:
#- jekyll-sitemap