author:      Enrique Marcos
name:        enrmarc
url:         "http://enrmarc.github.io"
biography:   "I’m Enrique, software developer based in <strike>Spain</strike>,
             Germany, and currently <strike>Java, Python</strike>, PHP, and JavaScript pay my bills."
keywords:    "software"
description: "This blog should work fine, except in terms of success."
highlighter: rouge
encoding:    "utf-8"
baseurl:     ""
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir:  assets/css

#permalink: /blog/:year/:month/:day/:title/
#gems:
#- jekyll-sitemap
